### ISSUE TITLE
Investigate current CI's

### ISSUE THREAD

**Issue by easternbloc** [UKHomeOffice/centralteam_ci#19]
Check if there are any other solutions available to run containerised builds other than drone and circleci.

High level checklist to be added to this ticket.

Must haves:
- [ ] Work with github and gitlab
- [ ] Tasks/Jobs are executed in docker containers
- [ ] Supports remote job triggering (ideally with custom parameters)
- [ ] ability to define own steps in a .dotbuild.file of some sort
- [ ] not deep tie in (ability to change CI easily)
- [ ] Parallel running?
- [ ] Hosted behind a firewall (on our own infrastructure)

Current CIs to review:
- drone
- circleci
- codeship? (only supports github and bitbucket)
- [wercker](http://wercker.com/)

**Comment by danielepolencic** [comment]
related: https://github.com/UKHomeOffice/centralteam_ci/pull/20

**Comment by easternbloc** [comment]
For some reason @danielepolencic I can't assign you to this ticket :(

**Comment by danielepolencic** [comment]
I can't push to this repo either

**Comment by easternbloc** [comment]
@danielepolencic sorted ;)

**Comment by danielepolencic** [comment]
I think we may want to consider https://concourse.ci/

| Name | Containerised | Gitlab/Github | License/Price | Remote Job triggering | Behind a firewall |
| --- | --- | --- | --- | --- | --- |
| [concourse](https://concourse.ci/) | Yes | Github only | Apache 2.0 | [Yes](https://github.com/starkandwayne/concourse-tutorial#07---trigger-jobs-with-the-concourse-api) | Yes |
| [Drone](https://github.com/drone/drone) | Yes | Github **OR** Gitlab | Apache 2.0 | No [0.4](http://readme.drone.io/devs/api/builds/) - [0.5](https://github.com/drone/drone/blob/master/server/swagger/files/swagger.yml) | Yes |
| [CircleCI](https://circleci.com/) | Yes | Github only | $750pm/16 agents/16 container + $50pm/ extra container | [Yes](https://circleci.com/docs/parameterized-builds/)<sup>2</sup> | [Yes](https://circleci.com/enterprise/) |
| [Codeship](https://codeship.com/) | Yes | Github only | $199pm 3pipelines 3agents | No<sup>3</sup> | [Yes](https://codeship.com/documentation/faq/enabling-access-to-servers/) |
| [Werker](http://wercker.com/) | Yes | Github only | From $350 / mo<sup>1<sup> | [Yes](http://devcenter.wercker.com/api/endpoints/builds.html) | [No](https://twitter.com/jmckenty/status/560535417695776769) |

[1] Werker is piloting paid subscriptions.
[2] Experimental feature
[3] Only restart and list jobs

**Comment by vaijab** [comment]
Simple CI/CD workflow as I imagine it (use http://asciiflow.com/ to edit)

```
+------------+
|code(nodejs)|                                         +----------------+
|   github   <--------+                                | kube files code|
|   push/PR  |        |                                | github         |
+-----+------+        |                                | push/PR        <--------+
      |             pass/                              |                |        |
     1|             fail                               +-------+--------+        |
      |               |                                        |                 |
+-----v------+        |                                        |                 |
|    CI      |    2   |                                        |                 |
|   build    +--------+                                        |4b               |5b
|   test/push|                                                 |               pass/fail
+-----+------+                                                 |                 |
      |                                                        |                 |
      |                                                        |                 |
     3|                     +------------+              +------v--------+        |
      |   artifact push     |            |       4a     |   CI(CD)      |        |
      +---------------------> quay /     +-------------->  deploy using +--------+
                            | artifactory|              |  kube files   |
                            |            |              |  repo         |
                            +------^-----+              +-------+-------+
                                   |                            |
                                   |                            |
                                   |                            |
                                   |             5a             |
                                   +----------------------------+
                                               pass/fail
```

**Comment by danielepolencic** [comment]
I wasn't able to deploy brp_app to concourse and eventually gave up. Overall it feels very complicated.

I spent some time looking at drone and I found this interesting discussion about [triggering remote jobs through an API](https://discuss.drone.io/t/solved-trigger-a-build-manually/116).

**Comment by easternbloc** [comment]
> I spent some time looking at drone and I found this interesting discussion about triggering remote jobs through an API.

Looks very interesting

**Comment by easternbloc** [comment]
@danielepolencic perhaps we could get rick to move the meeting on monday to the end of the day and we could pair on some of the remaining CI spikes?

**Comment by danielepolencic** [comment]
@easternbloc Yes, we can. ATM I'm playing with drone0.5 (master).

Also, I think we should add Travis CI to the list. The code is open source, there should be a way to self host it?

**Comment by danielepolencic** [comment]
https://github.com/lambci/lambci

![image](https://cloud.githubusercontent.com/assets/1130499/16699573/cca12d4a-454c-11e6-8b46-b35b4b5cdac2.png)

**Comment by danielepolencic** [comment]
Netflix: http://www.spinnaker.io/
Soundcloud: http://gotocon.com/dl/goto-zurich-2013/slides/AlexanderSimmerl_and_MattProud_BuildingAnInHouseHeroku.pdf
pinterest: https://github.com/pinterest/teletraan
airbnb: https://www.solanolabs.com/

**Comment by danielepolencic** [comment]
Stackstorm: https://github.com/StackStorm/st2

**Comment by czeczotka** [comment]
Hello, in the dev world there is definitely a lot of attention to TeamCity and Bamboo. Did we have a change to look at these?
https://www.jetbrains.com/teamcity/features/
https://www.atlassian.com/software/bamboo/features

**Comment by vaijab** [comment]
> Hello, in the dev world there is definitely a lot of attention to TeamCity and Bamboo. Did we have a change to look at these?
> https://www.jetbrains.com/teamcity/features/
> https://www.atlassian.com/software/bamboo/features

I don't have personal experience with neither of them, but as far as I know they are both monsters, like jenkins. A pain to run, a pain to scale and manage.

**Comment by vaijab** [comment]
We've picked drone.
